export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";

export const ADD_TO_CART="ADD_TO_CART";
export const DELETE_ITEM_CART="DELETE_ITEM_CART";
export const UPDATE_QUANTITY_ITEM="UPDATE_QUANTITY_ITEM";
